
@echo off
echo Starting Smart Resolve AI ML Service...
echo Creating virtual environment...
python -m venv venv
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Starting Flask server...
python app.py
pause
